title: Een aardingspin delen
hero_image: images/banner.png
description: Hoe deel je een aardingspin op je Raspberry Pi Pico
version: 4
listed: false
copyedit: false
last_tested: "2022-02-17"
steps:
  - 
    title: Een aardingspin delen
