title: Sharing a ground pin
hero_image: images/banner.png
description: sharing-a-ground-pin description
version: 4
listed: false
copyedit: false
last_tested: "2022-02-17"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
