title: Sharing a ground pin
hero_image: images/banner.png
description: How to share a ground pin on your Raspberry Pi Pico
version: 4
listed: false
copyedit: false
last_tested: "2022-02-17"
steps:
  - title: Sharing a ground pin
